---
title: "Exploratory Plot"
author: "Ben Sherwood"
date: '2022-10-25'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Normal Data
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("Nn",n,"var4xyTrue.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData5 <- subset(allData, tau==.5)
allData7 <- subset(allData, tau==.7)
```
## MSE Table 5
```{r}
mseTable <- allData5[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData5[,10:13],1,sum), allData5[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```

## MSE Table 7
```{r}
mseTable <- allData7[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData7[,10:13],1,sum), allData7[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Coverage 5
```{r}
coverageTable <- allData5[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```

## Coverage 7
```{r}
coverageTable <- allData7[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Hetero Data
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("Heteron",n,"var4xyTrue.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData5 <- subset(allData, tau==.5)
allData7 <- subset(allData, tau==.7)
```
## MSE Table 5
```{r}
mseTable <- allData5[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData5[,10:13],1,sum), allData5[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```

## MSE Table 7
```{r}
mseTable <- allData7[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData7[,10:13],1,sum), allData7[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Coverage 5
```{r}
coverageTable <- allData5[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```

## Coverage 7
```{r}
coverageTable <- allData7[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Asymetric Data
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("asymetricn",n,"var4xyTrue.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData5 <- subset(allData, tau==.5)
allData7 <- subset(allData, tau==.7)
```
## MSE Table 5
```{r}
mseTable <- allData5[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData5[,10:13],1,sum), allData5[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```

## MSE Table 7
```{r}
mseTable <- allData7[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData7[,10:13],1,sum), allData7[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Coverage 5
```{r}
coverageTable <- allData5[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```

## Coverage 7
```{r}
coverageTable <- allData7[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```



## More Present (Intercept 5) Hetero
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("Heteron",n,"mi5xyTrue.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData5 <- subset(allData, tau==.5)
allData7 <- subset(allData, tau==.7)
```
## MSE Table 5
```{r}
mseTable <- allData5[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData5[,10:13],1,sum), allData5[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```

## MSE Table 7
```{r}
mseTable <- allData7[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData7[,10:13],1,sum), allData7[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Coverage 5
```{r}
coverageTable <- allData5[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```

## Coverage 7
```{r}
coverageTable <- allData7[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Less Present (Intercept 3) Hetero
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("Heteron",n,"mi3xyTrue.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData5 <- subset(allData, tau==.5)
allData7 <- subset(allData, tau==.7)
```
## MSE Table 5
```{r}
mseTable <- allData5[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData5[,10:13],1,sum), allData5[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```

## MSE Table 7
```{r}
mseTable <- allData7[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData7[,10:13],1,sum), allData7[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Coverage 5
```{r}
coverageTable <- allData5[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```

## Coverage 7
```{r}
coverageTable <- allData7[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Hetero Misspecified
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("Heteron",n,"WMxyTrue.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData5 <- subset(allData, tau==.5)
allData7 <- subset(allData, tau==.7)
```
## MSE Table 5
```{r}
mseTable <- allData5[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData5[,10:13],1,sum), allData5[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```

## MSE Table 7
```{r}
mseTable <- allData7[,c(1,3,5,6:9)]
mseTable <- cbind(mseTable, apply(allData7[,10:13],1,sum), allData7[,14])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
print(mseResults, include.rownames=FALSE, hline.after=seq(3,18,3))
```


## Coverage 5
```{r}
coverageTable <- allData5[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```

## Coverage 7
```{r}
coverageTable <- allData7[,c(1,3,5,15:22)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,18,3))
```
