---
title: "Exploratory Plot"
author: "Ben Sherwood"
date: '2022-10-25'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting data
```{r}
allData <- NULL
for(n in c(100,500,1000)){
  allData <- rbind(allData, readRDS(paste0("NormalWild_n_",n,"_ycoef_-1_2022.RDS"))$results)
}
library(ggplot2)
library(reshape)
allData$Method <- paste(allData$Method,allData$x1Type)
```
## MSE Table
```{r}
mseTable <- allData[,c(1,3,5,7:10)]
mseTable <- cbind(mseTable, apply(allData[,11:14],1,sum), allData[,15])
for(i in 4:9){
  mseTable[,i] <- round(mseTable[,i],4)
}
mseTable
library(xtable)
mseResults <- xtable(mseTable, digits=c(0,0,0,0,4,4,4,4,4,4))
```

```{r, results='asis'}
print(mseResults, include.rownames=FALSE, hline.after=seq(3,24,3))
```

```{r}
coverageTable <- allData[,c(1,3,5,16:19,20:23)]
for(i in 4:ncol(coverageTable)){
  coverageTable[,i] <- round(coverageTable[,i],2)
}
coverageResults <- coverageTable[,1:3]
for(i in 1:4){
  coverageResults <- cbind(coverageResults, paste0(coverageTable[,i+7],"(",coverageTable[,i+3],")"))
}
```

```{r, results='asis'}
print(xtable(coverageResults, digits=c(0,0,0,0,2,2,2,2)), include.rownames=FALSE, hline.after=seq(3,24,3))

```
## Bias and Length 
<!-- ## Original Results -->
<!-- ```{r} -->
<!-- diffMissInter <- rbind(readRDS("Nn100var4ycoef-1_2022.RDS")$results, -->
<!--                  readRDS("Nn500var4ycoef-1_2022.RDS")$results, -->
<!--                  readRDS("Nn1000var4ycoef-1_2022.RDS")$results) -->
<!-- missPlotData <- melt(diffMissInter, id.vars=c("Method","tau","m","rho","n","ycoef")) -->


<!-- cData <- subset(missPlotData, variable %in% c("B_IntervalCoverage1","B_IntervalCoverage2","B_IntervalCoverage3","B_IntervalCoverage4")) -->

<!-- qplot(x=log(n),y=value, data=cData, color=Method) + facet_wrap(~variable*m) -->
<!-- ``` -->


